"""Central limits for text fields and payloads."""

MAX_INITIAL_REQUEST_CHARS = 16_384
MAX_CLARIFICATION_ANSWER_CHARS = 4_096
MAX_EDIT_INSTRUCTION_CHARS = 4_096
MAX_SESSION_TITLE_CHARS = 200
MAX_EXPORT_FOLDER_LABEL_CHARS = 80
MAX_DRAFT_BODY_CHARS = 256_000
MAX_REQUIREMENT_CARD_ITEM_CHARS = 8_192
MAX_REQUIREMENT_CARD_LIST_ITEMS = 64
MAX_AUDIT_MESSAGE_CHARS = 512
# Legacy presentation default for saved sessions; not a limit on the adaptive queue.
MAX_CLARIFICATION_QUESTIONS = 16
